javac SingleInheritance.java
java Main
javac MultiLevelInheritance.java
java Main
javac hierarchialInheritance.java
java Main
javac MultipleInheritance.java
java Main
javac Encapsulation.java
java Main
javac Abstraction.java
java Main
javac RunTImePolymorphism.java
java Main
javac CompileTimePolymorphism.java
java Main
javac thisRef.java
java Main
javac misPart1.java
java Main
javac misPart2.java
java Main
javac misPart3.java
java Main
javac misPart4.java
java base
javac strictfp.java
java Main
javac super.java
java Main
Pause